# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gAPAP72eq27mWaaDNytQoVz59SiJrNz
"""

from sympy import symbols, Matrix,expand

# Define symbols for R, L, C, s (Laplace variable)
L1,L2,C1,C2,s = symbols('L1 L2 C1 C2 s')
R = symbols('R')

# Create the 2x2 matrix for RLC circuit
# Assuming a series RLC circuit, the impedance matrix can be constructed as follows:
# Z = R + sL + 1/(sC)
# The off-diagonal elements are zero for a series circuit.
Z1 = Matrix([[1, L1*s+R],
            [0, 1]])
Z2 = Matrix([[1, L2*s+R],
            [0, 1]])
Z3 = Matrix([[1, 0],
            [C1*s, 1]])
Z4 = Matrix([[1, 0],
            [C2*s, 1]])

Z = Z1*Z3*Z2*Z4;
Z_dash=expand(Z[0,0])
Z_dash

Z